/* ============================================================================
 * Python prelude - constants and helper functions
 * Generated from prelude.py by scripts/prelude2c.py
 * ============================================================================ */

static const char *PY_PRELUDE_MODULE =
"import midi\n"
"import time as _time\n"
"\n"
"midi.ppp = 16\n"
"midi.pp = 33\n"
"midi.p = 49\n"
"midi.mp = 64\n"
"midi.mf = 80\n"
"midi.f = 96\n"
"midi.ff = 112\n"
"midi.fff = 127\n"
"\n"
"midi.whole = 2000\n"
"midi.half = 1000\n"
"midi.quarter = 500\n"
"midi.eighth = 250\n"
"midi.sixteenth = 125\n"
"\n"
"def _dotted(duration):\n"
"\n"
"    return int(duration * 1.5)\n"
"midi.dotted = _dotted\n"
"\n"
"midi._bpm = 120\n"
"\n"
"def _set_tempo(bpm):\n"
"\n"
"    midi._bpm = bpm\n"
"    midi._set_c_tempo(bpm)\n"
"    beat_ms = 60000 // bpm\n"
"    midi.quarter = beat_ms\n"
"    midi.half = beat_ms * 2\n"
"    midi.whole = beat_ms * 4\n"
"    midi.eighth = beat_ms // 2\n"
"    midi.sixteenth = beat_ms // 4\n"
"midi.set_tempo = _set_tempo\n"
"\n"
"def _get_tempo():\n"
"\n"
"    return midi._bpm\n"
"midi.get_tempo = _get_tempo\n"
"\n"
"def _bpm_to_ms(tempo):\n"
"\n"
"    return 60000 // tempo\n"
"midi.bpm = _bpm_to_ms\n"
"\n"
"def _sleep(ms):\n"
"\n"
"    _time.sleep(ms / 1000.0)\n"
"midi.sleep = _sleep\n"
"\n"
"def _rest(duration=None):\n"
"\n"
"    if duration is None:\n"
"        duration = midi.quarter\n"
"    _time.sleep(duration / 1000.0)\n"
"midi.rest = _rest\n"
"\n"
"midi.SCALE_MAJOR = (0, 2, 4, 5, 7, 9, 11)\n"
"midi.SCALE_IONIAN = midi.SCALE_MAJOR\n"
"midi.SCALE_DORIAN = (0, 2, 3, 5, 7, 9, 10)\n"
"midi.SCALE_PHRYGIAN = (0, 1, 3, 5, 7, 8, 10)\n"
"midi.SCALE_LYDIAN = (0, 2, 4, 6, 7, 9, 11)\n"
"midi.SCALE_MIXOLYDIAN = (0, 2, 4, 5, 7, 9, 10)\n"
"midi.SCALE_MINOR = (0, 2, 3, 5, 7, 8, 10)\n"
"midi.SCALE_AEOLIAN = midi.SCALE_MINOR\n"
"midi.SCALE_LOCRIAN = (0, 1, 3, 5, 6, 8, 10)\n"
"\n"
"midi.SCALE_HARMONIC_MINOR = (0, 2, 3, 5, 7, 8, 11)\n"
"midi.SCALE_MELODIC_MINOR = (0, 2, 3, 5, 7, 9, 11)\n"
"\n"
"midi.SCALE_PENTATONIC = (0, 2, 4, 7, 9)\n"
"midi.SCALE_PENTATONIC_MAJOR = midi.SCALE_PENTATONIC\n"
"midi.SCALE_PENTATONIC_MINOR = (0, 3, 5, 7, 10)\n"
"\n"
"midi.SCALE_BLUES = (0, 3, 5, 6, 7, 10)\n"
"\n"
"midi.SCALE_WHOLE_TONE = (0, 2, 4, 6, 8, 10)\n"
"midi.SCALE_CHROMATIC = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)\n"
"midi.SCALE_DIMINISHED_HW = (0, 1, 3, 4, 6, 7, 9, 10)\n"
"midi.SCALE_DIMINISHED_WH = (0, 2, 3, 5, 6, 8, 9, 11)\n"
"midi.SCALE_AUGMENTED = (0, 3, 4, 7, 8, 11)\n"
"\n"
"midi.SCALE_BEBOP_DOMINANT = (0, 2, 4, 5, 7, 9, 10, 11)\n"
"midi.SCALE_BEBOP_MAJOR = (0, 2, 4, 5, 7, 8, 9, 11)\n"
"midi.SCALE_BEBOP_MINOR = (0, 2, 3, 5, 7, 8, 9, 10)\n"
"\n"
"midi.SCALE_HUNGARIAN_MINOR = (0, 2, 3, 6, 7, 8, 11)\n"
"midi.SCALE_DOUBLE_HARMONIC = (0, 1, 4, 5, 7, 8, 11)\n"
"midi.SCALE_NEAPOLITAN_MAJOR = (0, 1, 3, 5, 7, 9, 11)\n"
"midi.SCALE_NEAPOLITAN_MINOR = (0, 1, 3, 5, 7, 8, 11)\n"
"midi.SCALE_PHRYGIAN_DOMINANT = (0, 1, 4, 5, 7, 8, 10)\n"
"midi.SCALE_PERSIAN = (0, 1, 4, 5, 6, 8, 11)\n"
"midi.SCALE_ALTERED = (0, 1, 3, 4, 6, 8, 10)\n"
"midi.SCALE_ENIGMATIC = (0, 1, 4, 6, 8, 10, 11)\n"
"\n"
"midi.SCALE_HIRAJOSHI = (0, 2, 3, 7, 8)\n"
"midi.SCALE_IN_SEN = (0, 1, 5, 7, 10)\n"
"midi.SCALE_IWATO = (0, 1, 5, 6, 10)\n"
"midi.SCALE_KUMOI = (0, 2, 3, 7, 9)\n"
"\n"
"midi.SCALE_EGYPTIAN = (0, 2, 5, 7, 10)\n"
"midi.SCALE_ROMANIAN_MINOR = (0, 2, 3, 6, 7, 9, 10)\n"
"midi.SCALE_SPANISH_8_TONE = (0, 1, 3, 4, 5, 6, 8, 10)\n"
"\n"
"midi.SCALE_MAQAM_HIJAZ = (0, 1, 4, 5, 7, 8, 10)\n"
"midi.SCALE_MAQAM_NAHAWAND = (0, 2, 3, 5, 7, 8, 11)\n"
"midi.SCALE_MAQAM_NIKRIZ = (0, 2, 3, 6, 7, 9, 10)\n"
"midi.SCALE_MAQAM_ATHAR_KURD = (0, 1, 3, 5, 6, 8, 10)\n"
"midi.SCALE_MAQAM_SHAWQ_AFZA = (0, 2, 3, 6, 7, 9, 11)\n"
"midi.SCALE_MAQAM_JIHARKAH = (0, 2, 4, 5, 7, 9, 10)\n"
"\n"
"midi.SCALE_RAGA_BHAIRAV = (0, 1, 4, 5, 7, 8, 11)\n"
"midi.SCALE_RAGA_TODI = (0, 1, 3, 6, 7, 8, 11)\n"
"midi.SCALE_RAGA_MARWA = (0, 1, 4, 6, 7, 9, 11)\n"
"midi.SCALE_RAGA_PURVI = (0, 1, 4, 6, 7, 8, 11)\n"
"midi.SCALE_RAGA_CHARUKESHI = (0, 2, 4, 5, 7, 8, 10)\n"
"midi.SCALE_RAGA_ASAVARI = (0, 2, 3, 5, 7, 8, 10)\n"
"midi.SCALE_RAGA_BILAWAL = (0, 2, 4, 5, 7, 9, 11)\n"
"midi.SCALE_RAGA_KHAMAJ = (0, 2, 4, 5, 7, 9, 10)\n"
"midi.SCALE_RAGA_KALYAN = (0, 2, 4, 6, 7, 9, 11)\n"
"midi.SCALE_RAGA_BHIMPALASI = (0, 3, 5, 7, 10)\n"
"midi.SCALE_RAGA_DARBARI = (0, 2, 3, 5, 7, 8, 9)\n"
"\n"
"midi.SCALE_MAQAM_BAYATI_CENTS = (0, 150, 300, 500, 700, 800, 1000)\n"
"midi.SCALE_MAQAM_RAST_CENTS = (0, 200, 350, 500, 700, 900, 1050)\n"
"midi.SCALE_MAQAM_SABA_CENTS = (0, 150, 300, 400, 500, 700, 800)\n"
"midi.SCALE_MAQAM_SIKAH_CENTS = (0, 150, 350, 500, 650, 850, 1000)\n"
"midi.SCALE_MAQAM_HUZAM_CENTS = (0, 150, 350, 500, 700, 850, 1050)\n"
"midi.SCALE_MAQAM_IRAQ_CENTS = (0, 150, 350, 500, 700, 850, 1000)\n"
"midi.SCALE_MAQAM_BASTANIKAR_CENTS = (0, 150, 350, 500, 700, 800, 1000)\n"
"\n"
"midi.SCALE_MAKAM_USSAK_CENTS = (0, 150, 300, 500, 700, 800, 1000)\n"
"midi.SCALE_MAKAM_HUSEYNI_CENTS = (0, 150, 300, 500, 700, 900, 1000)\n"
"\n"
"midi.SCALE_SHRUTI_CENTS = (0, 90, 112, 182, 204, 294, 316, 386, 408, 498, 520, 590,\n"
"                           612, 702, 792, 814, 884, 906, 996, 1018, 1088, 1110)\n"
"\n"
"midi.scales = {\n"
"    'major': midi.SCALE_MAJOR,\n"
"    'ionian': midi.SCALE_IONIAN,\n"
"    'dorian': midi.SCALE_DORIAN,\n"
"    'phrygian': midi.SCALE_PHRYGIAN,\n"
"    'lydian': midi.SCALE_LYDIAN,\n"
"    'mixolydian': midi.SCALE_MIXOLYDIAN,\n"
"    'minor': midi.SCALE_MINOR,\n"
"    'aeolian': midi.SCALE_AEOLIAN,\n"
"    'locrian': midi.SCALE_LOCRIAN,\n"
"    'harmonic_minor': midi.SCALE_HARMONIC_MINOR,\n"
"    'melodic_minor': midi.SCALE_MELODIC_MINOR,\n"
"    'pentatonic': midi.SCALE_PENTATONIC,\n"
"    'pentatonic_major': midi.SCALE_PENTATONIC_MAJOR,\n"
"    'pentatonic_minor': midi.SCALE_PENTATONIC_MINOR,\n"
"    'blues': midi.SCALE_BLUES,\n"
"    'whole_tone': midi.SCALE_WHOLE_TONE,\n"
"    'chromatic': midi.SCALE_CHROMATIC,\n"
"    'diminished_hw': midi.SCALE_DIMINISHED_HW,\n"
"    'diminished_wh': midi.SCALE_DIMINISHED_WH,\n"
"    'augmented': midi.SCALE_AUGMENTED,\n"
"    'bebop_dominant': midi.SCALE_BEBOP_DOMINANT,\n"
"    'bebop_major': midi.SCALE_BEBOP_MAJOR,\n"
"    'bebop_minor': midi.SCALE_BEBOP_MINOR,\n"
"    'hungarian_minor': midi.SCALE_HUNGARIAN_MINOR,\n"
"    'double_harmonic': midi.SCALE_DOUBLE_HARMONIC,\n"
"    'neapolitan_major': midi.SCALE_NEAPOLITAN_MAJOR,\n"
"    'neapolitan_minor': midi.SCALE_NEAPOLITAN_MINOR,\n"
"    'phrygian_dominant': midi.SCALE_PHRYGIAN_DOMINANT,\n"
"    'persian': midi.SCALE_PERSIAN,\n"
"    'altered': midi.SCALE_ALTERED,\n"
"    'enigmatic': midi.SCALE_ENIGMATIC,\n"
"    'hirajoshi': midi.SCALE_HIRAJOSHI,\n"
"    'in_sen': midi.SCALE_IN_SEN,\n"
"    'iwato': midi.SCALE_IWATO,\n"
"    'kumoi': midi.SCALE_KUMOI,\n"
"    'egyptian': midi.SCALE_EGYPTIAN,\n"
"    'romanian_minor': midi.SCALE_ROMANIAN_MINOR,\n"
"    'spanish_8_tone': midi.SCALE_SPANISH_8_TONE,\n"
"    'maqam_hijaz': midi.SCALE_MAQAM_HIJAZ,\n"
"    'maqam_nahawand': midi.SCALE_MAQAM_NAHAWAND,\n"
"    'maqam_nikriz': midi.SCALE_MAQAM_NIKRIZ,\n"
"    'maqam_athar_kurd': midi.SCALE_MAQAM_ATHAR_KURD,\n"
"    'maqam_shawq_afza': midi.SCALE_MAQAM_SHAWQ_AFZA,\n"
"    'maqam_jiharkah': midi.SCALE_MAQAM_JIHARKAH,\n"
"    'raga_bhairav': midi.SCALE_RAGA_BHAIRAV,\n"
"    'raga_todi': midi.SCALE_RAGA_TODI,\n"
"    'raga_marwa': midi.SCALE_RAGA_MARWA,\n"
"    'raga_purvi': midi.SCALE_RAGA_PURVI,\n"
"    'raga_charukeshi': midi.SCALE_RAGA_CHARUKESHI,\n"
"    'raga_asavari': midi.SCALE_RAGA_ASAVARI,\n"
"    'raga_bilawal': midi.SCALE_RAGA_BILAWAL,\n"
"    'raga_khamaj': midi.SCALE_RAGA_KHAMAJ,\n"
"    'raga_kalyan': midi.SCALE_RAGA_KALYAN,\n"
"    'raga_bhimpalasi': midi.SCALE_RAGA_BHIMPALASI,\n"
"    'raga_darbari': midi.SCALE_RAGA_DARBARI,\n"
"}\n"
"\n"
"midi.scales_cents = {\n"
"    'maqam_bayati': midi.SCALE_MAQAM_BAYATI_CENTS,\n"
"    'maqam_rast': midi.SCALE_MAQAM_RAST_CENTS,\n"
"    'maqam_saba': midi.SCALE_MAQAM_SABA_CENTS,\n"
"    'maqam_sikah': midi.SCALE_MAQAM_SIKAH_CENTS,\n"
"    'maqam_huzam': midi.SCALE_MAQAM_HUZAM_CENTS,\n"
"    'maqam_iraq': midi.SCALE_MAQAM_IRAQ_CENTS,\n"
"    'maqam_bastanikar': midi.SCALE_MAQAM_BASTANIKAR_CENTS,\n"
"    'makam_ussak': midi.SCALE_MAKAM_USSAK_CENTS,\n"
"    'makam_huseyni': midi.SCALE_MAKAM_HUSEYNI_CENTS,\n"
"    'shruti': midi.SCALE_SHRUTI_CENTS,\n"
"}\n"
"\n"
"def _get_scale(name):\n"
"\n"
"    if name not in midi.scales:\n"
"        raise ValueError(f\"Unknown scale: {name}\")\n"
"    return midi.scales[name]\n"
"\n"
"def _scale(root, name):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return midi.build_scale(root, _get_scale(name))\n"
"midi.scale = _scale\n"
"\n"
"def _degree(root, name, n):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return midi.scale_degree(root, _get_scale(name), n)\n"
"midi.degree = _degree\n"
"\n"
"def _in_scale_named(pitch, root, name):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return midi.in_scale(pitch, root, _get_scale(name))\n"
"midi.in_scale_named = _in_scale_named\n"
"\n"
"def _quantize(pitch, root, name):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return midi.quantize_to_scale(pitch, root, _get_scale(name))\n"
"midi.quantize = _quantize\n"
"\n"
"def _cents_to_note(root, cents):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    semitones = cents // 100\n"
"    bend_cents = cents % 100\n"
"    if bend_cents > 50:\n"
"        semitones += 1\n"
"        bend_cents -= 100\n"
"    return (root + semitones, bend_cents)\n"
"midi.cents_to_note = _cents_to_note\n"
"\n"
"def _major(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 7]\n"
"midi.major = _major\n"
"\n"
"def _minor(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 3, root + 7]\n"
"midi.minor = _minor\n"
"\n"
"def _dim(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 3, root + 6]\n"
"midi.dim = _dim\n"
"\n"
"def _aug(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 8]\n"
"midi.aug = _aug\n"
"\n"
"def _dom7(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 7, root + 10]\n"
"midi.dom7 = _dom7\n"
"\n"
"def _maj7(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 7, root + 11]\n"
"midi.maj7 = _maj7\n"
"\n"
"def _min7(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 3, root + 7, root + 10]\n"
"midi.min7 = _min7\n"
"\n"
"def _transpose(pitch, semitones):\n"
"\n"
"    if isinstance(pitch, str):\n"
"        pitch = midi.note(pitch)\n"
"    return pitch + semitones\n"
"midi.transpose = _transpose\n"
"\n"
"def _octave_up(pitch):\n"
"\n"
"    return _transpose(pitch, 12)\n"
"midi.octave_up = _octave_up\n"
"\n"
"def _octave_down(pitch):\n"
"\n"
"    return _transpose(pitch, -12)\n"
"midi.octave_down = _octave_down\n"
"\n"
"for _oct in range(9):\n"
"    setattr(midi, f'c{_oct}', 12 + _oct * 12)\n"
"    setattr(midi, f'cs{_oct}', 13 + _oct * 12)\n"
"    setattr(midi, f'db{_oct}', 13 + _oct * 12)\n"
"    setattr(midi, f'd{_oct}', 14 + _oct * 12)\n"
"    setattr(midi, f'ds{_oct}', 15 + _oct * 12)\n"
"    setattr(midi, f'eb{_oct}', 15 + _oct * 12)\n"
"    setattr(midi, f'e{_oct}', 16 + _oct * 12)\n"
"    setattr(midi, f'f{_oct}', 17 + _oct * 12)\n"
"    setattr(midi, f'fs{_oct}', 18 + _oct * 12)\n"
"    setattr(midi, f'gb{_oct}', 18 + _oct * 12)\n"
"    setattr(midi, f'g{_oct}', 19 + _oct * 12)\n"
"    setattr(midi, f'gs{_oct}', 20 + _oct * 12)\n"
"    setattr(midi, f'ab{_oct}', 20 + _oct * 12)\n"
"    setattr(midi, f'a{_oct}', 21 + _oct * 12)\n"
"    setattr(midi, f'as{_oct}', 22 + _oct * 12)\n"
"    setattr(midi, f'bb{_oct}', 22 + _oct * 12)\n"
"    setattr(midi, f'b{_oct}', 23 + _oct * 12)\n"
"del _oct\n"
"\n"
"midi.CC_MODULATION = 1\n"
"midi.CC_BREATH = 2\n"
"midi.CC_VOLUME = 7\n"
"midi.CC_PAN = 10\n"
"midi.CC_EXPRESSION = 11\n"
"midi.CC_SUSTAIN = 64\n"
"midi.CC_REVERB = 91\n"
"midi.CC_CHORUS = 93\n"
"\n"
"def _arpeggio(self, pitches, velocity=80, note_duration=None, spacing=None, channel=1):\n"
"\n"
"    if note_duration is None:\n"
"        note_duration = midi.eighth\n"
"    if spacing is None:\n"
"        spacing = note_duration\n"
"    for p in pitches:\n"
"        self.note(p, velocity, note_duration, channel)\n"
"        if spacing > note_duration:\n"
"            midi.sleep(spacing - note_duration)\n"
"midi.MidiOut.arpeggio = _arpeggio\n"
"\n"
"def _modulation(self, value, channel=1):\n"
"\n"
"    self.cc(1, value, channel)\n"
"midi.MidiOut.modulation = _modulation\n"
"\n"
"def _volume(self, value, channel=1):\n"
"\n"
"    self.cc(7, value, channel)\n"
"midi.MidiOut.volume = _volume\n"
"\n"
"def _pan(self, value, channel=1):\n"
"\n"
"    self.cc(10, value, channel)\n"
"midi.MidiOut.pan = _pan\n"
"\n"
"def _sustain(self, on=True, channel=1):\n"
"\n"
"    self.cc(64, 127 if on else 0, channel)\n"
"midi.MidiOut.sustain = _sustain\n"
"\n"
"def _next_random(seed):\n"
"\n"
"    next_seed = (seed * 1103515245 + 12345) % 2147483648\n"
"    value = next_seed // 65536\n"
"    return (value, next_seed)\n"
"midi.next_random = _next_random\n"
"\n"
"def _random_range(seed, lo, hi):\n"
"\n"
"    if lo >= hi:\n"
"        return (lo, seed)\n"
"    r, next_seed = _next_random(seed)\n"
"    return (lo + (r % (hi - lo + 1)), next_seed)\n"
"midi.random_range = _random_range\n"
"\n"
"def _random_list(seed, n, lo, hi):\n"
"\n"
"    result = []\n"
"    s = seed\n"
"    for _ in range(n):\n"
"        r, s = _random_range(s, lo, hi)\n"
"        result.append(r)\n"
"    return (result, s)\n"
"midi.random_list = _random_list\n"
"\n"
"def _euclidean(hits, steps):\n"
"\n"
"    if hits <= 0:\n"
"        return [False] * steps\n"
"    if hits >= steps:\n"
"        return [True] * steps\n"
"\n"
"    seqs = [[True] for _ in range(hits)]\n"
"    remainder = [[False] for _ in range(steps - hits)]\n"
"\n"
"    while len(remainder) > 1:\n"
"        new_seqs = []\n"
"        min_len = min(len(seqs), len(remainder))\n"
"        for i in range(min_len):\n"
"            new_seqs.append(seqs[i] + remainder[i])\n"
"        new_remainder = seqs[min_len:] + remainder[min_len:]\n"
"        seqs = new_seqs\n"
"        remainder = new_remainder\n"
"\n"
"    result = []\n"
"    for seq in seqs:\n"
"        result.extend(seq)\n"
"    for seq in remainder:\n"
"        result.extend(seq)\n"
"    return result\n"
"midi.euclidean = _euclidean\n"
"\n"
"def _arp_up(lst):\n"
"\n"
"    return list(lst)\n"
"midi.arp_up = _arp_up\n"
"\n"
"def _arp_down(lst):\n"
"\n"
"    return list(reversed(lst))\n"
"midi.arp_down = _arp_down\n"
"\n"
"def _arp_up_down(lst):\n"
"\n"
"    if len(lst) <= 1:\n"
"        return list(lst)\n"
"    result = list(lst)\n"
"    result.extend(reversed(lst[1:-1]))\n"
"    return result\n"
"midi.arp_up_down = _arp_up_down\n"
"\n"
"def _retrograde(lst):\n"
"\n"
"    return list(reversed(lst))\n"
"midi.retrograde = _retrograde\n"
"\n"
"def _invert(lst, axis):\n"
"\n"
"    return [2 * axis - pitch for pitch in lst]\n"
"midi.invert = _invert\n"
"\n"
"def _shuffle(seed, lst):\n"
"\n"
"    result = list(lst)\n"
"    s = seed\n"
"    for i in range(len(result) - 1, 0, -1):\n"
"        j, s = _random_range(s, 0, i)\n"
"        result[i], result[j] = result[j], result[i]\n"
"    return result\n"
"midi.shuffle = _shuffle\n"
"\n"
"def _pick(seed, lst):\n"
"\n"
"    if len(lst) == 0:\n"
"        return None\n"
"    idx, _ = _random_range(seed, 0, len(lst) - 1)\n"
"    return lst[idx]\n"
"midi.pick = _pick\n"
"\n"
"def _pick_n(seed, n, lst):\n"
"\n"
"    if len(lst) == 0:\n"
"        return []\n"
"    result = []\n"
"    s = seed\n"
"    for _ in range(n):\n"
"        idx, s = _random_range(s, 0, len(lst) - 1)\n"
"        result.append(lst[idx])\n"
"    return result\n"
"midi.pick_n = _pick_n\n"
"\n"
"def _random_walk(seed, start, max_step, n):\n"
"\n"
"    result = []\n"
"    s = seed\n"
"    pitch = start\n"
"    for _ in range(n):\n"
"        result.append(pitch)\n"
"        step, s = _random_range(s, -max_step, max_step)\n"
"        pitch = max(0, min(127, pitch + step))\n"
"    return result\n"
"midi.random_walk = _random_walk\n"
"\n"
"def _drunk_walk(seed, start, scale_pitches, max_degrees, n):\n"
"\n"
"    if len(scale_pitches) == 0:\n"
"        return []\n"
"\n"
"    def find_closest(p, pitches):\n"
"        best_idx = 0\n"
"        best_dist = abs(p - pitches[0])\n"
"        for i in range(1, len(pitches)):\n"
"            dist = abs(p - pitches[i])\n"
"            if dist < best_dist:\n"
"                best_dist = dist\n"
"                best_idx = i\n"
"        return best_idx\n"
"\n"
"    result = []\n"
"    s = seed\n"
"    idx = find_closest(start, scale_pitches)\n"
"\n"
"    for _ in range(n):\n"
"        result.append(scale_pitches[idx])\n"
"        step, s = _random_range(s, -max_degrees, max_degrees)\n"
"        idx = max(0, min(len(scale_pitches) - 1, idx + step))\n"
"    return result\n"
"midi.drunk_walk = _drunk_walk\n"
"\n"
"def _weighted_pick(seed, weights):\n"
"\n"
"    total = 0\n"
"    for w in weights:\n"
"        total += w[1]\n"
"    if total <= 0:\n"
"        return None\n"
"    r, _ = _random_range(seed, 1, total)\n"
"    cumulative = 0\n"
"    for w in weights:\n"
"        cumulative += w[1]\n"
"        if r <= cumulative:\n"
"            return w[0]\n"
"    return weights[-1][0]\n"
"midi.weighted_pick = _weighted_pick\n"
"\n"
"def _chance(seed, probability):\n"
"\n"
"    r, next_seed = _random_range(seed, 0, 99)\n"
"    return (r < probability, next_seed)\n"
"midi.chance = _chance\n"
"\n"
"def _play(out, pitch, velocity=None, duration=None, channel=1):\n"
"\n"
"    if velocity is None:\n"
"        velocity = midi.mf\n"
"    if duration is None:\n"
"        duration = midi.quarter\n"
"    if isinstance(pitch, str):\n"
"        pitch = midi.note(pitch)\n"
"    out.note_on(pitch, velocity, channel)\n"
"    yield duration\n"
"    out.note_off(pitch, 0, channel)\n"
"midi.play = _play\n"
"\n"
"def _play_chord(out, pitches, velocity=None, duration=None, channel=1):\n"
"\n"
"    if velocity is None:\n"
"        velocity = midi.mf\n"
"    if duration is None:\n"
"        duration = midi.quarter\n"
"\n"
"    resolved = []\n"
"    for p in pitches:\n"
"        if isinstance(p, str):\n"
"            resolved.append(midi.note(p))\n"
"        else:\n"
"            resolved.append(p)\n"
"\n"
"    for p in resolved:\n"
"        out.note_on(p, velocity, channel)\n"
"    yield duration\n"
"\n"
"    for p in resolved:\n"
"        out.note_off(p, 0, channel)\n"
"midi.play_chord = _play_chord\n"
"\n"
"def _play_arp(out, pitches, velocity=None, note_duration=None, spacing=None, channel=1):\n"
"\n"
"    if velocity is None:\n"
"        velocity = midi.mf\n"
"    if note_duration is None:\n"
"        note_duration = midi.eighth\n"
"    if spacing is None:\n"
"        spacing = note_duration\n"
"    for p in pitches:\n"
"        for ms in _play(out, p, velocity, note_duration, channel):\n"
"            yield ms\n"
"        if spacing > note_duration:\n"
"            yield spacing - note_duration\n"
"midi.play_arp = _play_arp\n"
"\n"
"def _wait(ms):\n"
"\n"
"    yield ms\n"
"midi.wait = _wait\n"
"\n"
"def _ms(n):\n"
"\n"
"    return n\n"
"midi.ms = _ms\n"
"\n"
"midi.yield_ms = _ms\n";
