/* ============================================================================
 * Python prelude - constants and helper functions
 * Generated from prelude.py by scripts/prelude2c.py
 * ============================================================================ */

static const char *PY_PRELUDE_MODULE =
"import midi\n"
"import time as _time\n"
"\n"
"midi.ppp = 16\n"
"midi.pp = 33\n"
"midi.p = 49\n"
"midi.mp = 64\n"
"midi.mf = 80\n"
"midi.f = 96\n"
"midi.ff = 112\n"
"midi.fff = 127\n"
"\n"
"midi.whole = 2000\n"
"midi.half = 1000\n"
"midi.quarter = 500\n"
"midi.eighth = 250\n"
"midi.sixteenth = 125\n"
"\n"
"def _dotted(duration):\n"
"\n"
"    return int(duration * 1.5)\n"
"midi.dotted = _dotted\n"
"\n"
"midi._bpm = 120\n"
"\n"
"def _set_tempo(bpm):\n"
"\n"
"    midi._bpm = bpm\n"
"    beat_ms = 60000 // bpm\n"
"    midi.quarter = beat_ms\n"
"    midi.half = beat_ms * 2\n"
"    midi.whole = beat_ms * 4\n"
"    midi.eighth = beat_ms // 2\n"
"    midi.sixteenth = beat_ms // 4\n"
"midi.set_tempo = _set_tempo\n"
"\n"
"def _get_tempo():\n"
"\n"
"    return midi._bpm\n"
"midi.get_tempo = _get_tempo\n"
"\n"
"def _bpm_to_ms(tempo):\n"
"\n"
"    return 60000 // tempo\n"
"midi.bpm = _bpm_to_ms\n"
"\n"
"def _sleep(ms):\n"
"\n"
"    _time.sleep(ms / 1000.0)\n"
"midi.sleep = _sleep\n"
"\n"
"def _rest(duration=None):\n"
"\n"
"    if duration is None:\n"
"        duration = midi.quarter\n"
"    _time.sleep(duration / 1000.0)\n"
"midi.rest = _rest\n"
"\n"
"def _major(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 7]\n"
"midi.major = _major\n"
"\n"
"def _minor(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 3, root + 7]\n"
"midi.minor = _minor\n"
"\n"
"def _dim(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 3, root + 6]\n"
"midi.dim = _dim\n"
"\n"
"def _aug(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 8]\n"
"midi.aug = _aug\n"
"\n"
"def _dom7(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 7, root + 10]\n"
"midi.dom7 = _dom7\n"
"\n"
"def _maj7(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 4, root + 7, root + 11]\n"
"midi.maj7 = _maj7\n"
"\n"
"def _min7(root):\n"
"\n"
"    if isinstance(root, str):\n"
"        root = midi.note(root)\n"
"    return [root, root + 3, root + 7, root + 10]\n"
"midi.min7 = _min7\n"
"\n"
"def _transpose(pitch, semitones):\n"
"\n"
"    if isinstance(pitch, str):\n"
"        pitch = midi.note(pitch)\n"
"    return pitch + semitones\n"
"midi.transpose = _transpose\n"
"\n"
"def _octave_up(pitch):\n"
"\n"
"    return _transpose(pitch, 12)\n"
"midi.octave_up = _octave_up\n"
"\n"
"def _octave_down(pitch):\n"
"\n"
"    return _transpose(pitch, -12)\n"
"midi.octave_down = _octave_down\n"
"\n"
"for _oct in range(9):\n"
"    setattr(midi, f'c{_oct}', 12 + _oct * 12)\n"
"    setattr(midi, f'cs{_oct}', 13 + _oct * 12)\n"
"    setattr(midi, f'db{_oct}', 13 + _oct * 12)\n"
"    setattr(midi, f'd{_oct}', 14 + _oct * 12)\n"
"    setattr(midi, f'ds{_oct}', 15 + _oct * 12)\n"
"    setattr(midi, f'eb{_oct}', 15 + _oct * 12)\n"
"    setattr(midi, f'e{_oct}', 16 + _oct * 12)\n"
"    setattr(midi, f'f{_oct}', 17 + _oct * 12)\n"
"    setattr(midi, f'fs{_oct}', 18 + _oct * 12)\n"
"    setattr(midi, f'gb{_oct}', 18 + _oct * 12)\n"
"    setattr(midi, f'g{_oct}', 19 + _oct * 12)\n"
"    setattr(midi, f'gs{_oct}', 20 + _oct * 12)\n"
"    setattr(midi, f'ab{_oct}', 20 + _oct * 12)\n"
"    setattr(midi, f'a{_oct}', 21 + _oct * 12)\n"
"    setattr(midi, f'as{_oct}', 22 + _oct * 12)\n"
"    setattr(midi, f'bb{_oct}', 22 + _oct * 12)\n"
"    setattr(midi, f'b{_oct}', 23 + _oct * 12)\n"
"del _oct\n"
"\n"
"midi.CC_MODULATION = 1\n"
"midi.CC_BREATH = 2\n"
"midi.CC_VOLUME = 7\n"
"midi.CC_PAN = 10\n"
"midi.CC_EXPRESSION = 11\n"
"midi.CC_SUSTAIN = 64\n"
"midi.CC_REVERB = 91\n"
"midi.CC_CHORUS = 93\n"
"\n"
"def _arpeggio(self, pitches, velocity=80, note_duration=None, spacing=None, channel=1):\n"
"\n"
"    if note_duration is None:\n"
"        note_duration = midi.eighth\n"
"    if spacing is None:\n"
"        spacing = note_duration\n"
"    for p in pitches:\n"
"        self.note(p, velocity, note_duration, channel)\n"
"        if spacing > note_duration:\n"
"            midi.sleep(spacing - note_duration)\n"
"midi.MidiOut.arpeggio = _arpeggio\n"
"\n"
"def _modulation(self, value, channel=1):\n"
"\n"
"    self.cc(1, value, channel)\n"
"midi.MidiOut.modulation = _modulation\n"
"\n"
"def _volume(self, value, channel=1):\n"
"\n"
"    self.cc(7, value, channel)\n"
"midi.MidiOut.volume = _volume\n"
"\n"
"def _pan(self, value, channel=1):\n"
"\n"
"    self.cc(10, value, channel)\n"
"midi.MidiOut.pan = _pan\n"
"\n"
"def _sustain(self, on=True, channel=1):\n"
"\n"
"    self.cc(64, 127 if on else 0, channel)\n"
"midi.MidiOut.sustain = _sustain\n";
