/* ============================================================================
 * Lua prelude - constants and helper functions
 * Generated from prelude.lua by scripts/prelude2c.py
 * ============================================================================ */

static const char *LUA_PRELUDE_MODULE =
"-- Pitch constants\n"
"for oct = 0, 8 do\n"
"  midi['c'..oct] = 12 + oct * 12\n"
"  midi['cs'..oct] = 13 + oct * 12\n"
"  midi['d'..oct] = 14 + oct * 12\n"
"  midi['ds'..oct] = 15 + oct * 12\n"
"  midi['e'..oct] = 16 + oct * 12\n"
"  midi['f'..oct] = 17 + oct * 12\n"
"  midi['fs'..oct] = 18 + oct * 12\n"
"  midi['g'..oct] = 19 + oct * 12\n"
"  midi['gs'..oct] = 20 + oct * 12\n"
"  midi['a'..oct] = 21 + oct * 12\n"
"  midi['as'..oct] = 22 + oct * 12\n"
"  midi['b'..oct] = 23 + oct * 12\n"
"  -- Flat aliases\n"
"  midi['db'..oct] = 13 + oct * 12\n"
"  midi['eb'..oct] = 15 + oct * 12\n"
"  midi['gb'..oct] = 18 + oct * 12\n"
"  midi['ab'..oct] = 20 + oct * 12\n"
"  midi['bb'..oct] = 22 + oct * 12\n"
"end\n"
"\n"
"-- Dynamics (velocity values)\n"
"midi.ppp = 16\n"
"midi.pp = 33\n"
"midi.p = 49\n"
"midi.mp = 64\n"
"midi.mf = 80\n"
"midi.f = 96\n"
"midi.ff = 112\n"
"midi.fff = 127\n"
"\n"
"-- Duration constants (ms at 120 BPM)\n"
"midi.whole = 2000\n"
"midi.half = 1000\n"
"midi.quarter = 500\n"
"midi.eighth = 250\n"
"midi.sixteenth = 125\n"
"\n"
"-- Tempo state\n"
"midi._tempo = 120\n"
"\n"
"function midi.set_tempo(bpm)\n"
"  midi._tempo = bpm\n"
"  local q = math.floor(60000 / bpm)\n"
"  midi.quarter = q\n"
"  midi.whole = q * 4\n"
"  midi.half = q * 2\n"
"  midi.eighth = math.floor(q / 2)\n"
"  midi.sixteenth = math.floor(q / 4)\n"
"end\n"
"\n"
"function midi.get_tempo()\n"
"  return midi._tempo\n"
"end\n"
"\n"
"function midi.bpm(tempo)\n"
"  return math.floor(60000 / tempo)\n"
"end\n"
"\n"
"function midi.dotted(dur)\n"
"  return math.floor(dur * 1.5)\n"
"end\n"
"\n"
"function midi.rest(dur)\n"
"  midi.sleep(dur or midi.quarter)\n"
"end\n"
"\n"
"-- Global aliases for concise syntax\n"
"-- Pitch constants as globals\n"
"for oct = 0, 8 do\n"
"  _G['c'..oct] = midi['c'..oct]\n"
"  _G['cs'..oct] = midi['cs'..oct]\n"
"  _G['d'..oct] = midi['d'..oct]\n"
"  _G['ds'..oct] = midi['ds'..oct]\n"
"  _G['e'..oct] = midi['e'..oct]\n"
"  _G['f'..oct] = midi['f'..oct]\n"
"  _G['fs'..oct] = midi['fs'..oct]\n"
"  _G['g'..oct] = midi['g'..oct]\n"
"  _G['gs'..oct] = midi['gs'..oct]\n"
"  _G['a'..oct] = midi['a'..oct]\n"
"  _G['as'..oct] = midi['as'..oct]\n"
"  _G['b'..oct] = midi['b'..oct]\n"
"  _G['db'..oct] = midi['db'..oct]\n"
"  _G['eb'..oct] = midi['eb'..oct]\n"
"  _G['gb'..oct] = midi['gb'..oct]\n"
"  _G['ab'..oct] = midi['ab'..oct]\n"
"  _G['bb'..oct] = midi['bb'..oct]\n"
"end\n"
"\n"
"-- Dynamics as globals\n"
"ppp, pp, p, mp, mf, f, ff, fff = midi.ppp, midi.pp, midi.p, midi.mp, midi.mf, midi.f, midi.ff, midi.fff\n"
"\n"
"-- Durations as globals\n"
"whole, half, quarter, eighth, sixteenth = midi.whole, midi.half, midi.quarter, midi.eighth, midi.sixteenth\n"
"\n"
"-- Chord builders as globals\n"
"major, minor, dim, aug, dom7, maj7, min7 = midi.major, midi.minor, midi.dim, midi.aug, midi.dom7, midi.maj7, midi.min7\n"
"\n"
"-- Other utilities as globals\n"
"transpose, octave_up, octave_down = midi.transpose, midi.octave_up, midi.octave_down\n"
"dotted, rest, sleep = midi.dotted, midi.rest, midi.sleep\n"
"\n"
"-- Global help function\n"
"function help() midi.help() end\n"
"\n"
"-- REPL convenience: global midi output\n"
"midi._out = nil\n"
"\n"
"function open(arg)\n"
"  if midi._out then midi._out:close() end\n"
"  midi._out = midi.open(arg)\n"
"  return midi._out\n"
"end\n"
"\n"
"function close()\n"
"  if midi._out then\n"
"    midi._out:close()\n"
"    midi._out = nil\n"
"  end\n"
"end\n"
"\n"
"function n(pitch, vel, dur, ch)\n"
"  if not midi._out then error('No MIDI port open. Use open() first.') end\n"
"  midi._out:note(pitch, vel or midi.mf, dur or midi.quarter, ch or 1)\n"
"end\n"
"\n"
"function ch(pitches, vel, dur, channel)\n"
"  if not midi._out then error('No MIDI port open. Use open() first.') end\n"
"  midi._out:chord(pitches, vel or midi.mf, dur or midi.quarter, channel or 1)\n"
"end\n"
"\n"
"function arp(pitches, vel, dur, channel)\n"
"  if not midi._out then error('No MIDI port open. Use open() first.') end\n"
"  midi._out:arpeggio(pitches, vel or midi.mf, dur or midi.eighth, channel or 1)\n"
"end\n";
