/* ============================================================================
 * Scheme prelude - constants and helper functions
 * Generated from prelude.scm by scripts/prelude2c.py
 * ============================================================================ */

static const char *SCHEME_PRELUDE_MODULE =
";; Dynamics (velocity values)\n"
"(define ppp 16)\n"
"(define pp 33)\n"
"(define p 49)\n"
"(define mp 64)\n"
"(define mf 80)\n"
"(define f 96)\n"
"(define ff 112)\n"
"(define fff 127)\n"
"\n"
";; Durations (milliseconds at 120 BPM)\n"
"(define whole 2000)\n"
"(define half 1000)\n"
"(define quarter 500)\n"
"(define eighth 250)\n"
"(define sixteenth 125)\n"
"\n"
"(define (dotted dur) (floor (* dur 1.5)))\n"
"\n"
";; Tempo\n"
"(define *bpm* 120)\n"
"\n"
"(define (set-tempo! bpm)\n"
"  (set! *bpm* bpm)\n"
"  (let ((beat-ms (floor (/ 60000 bpm))))\n"
"    (set! quarter beat-ms)\n"
"    (set! half (* beat-ms 2))\n"
"    (set! whole (* beat-ms 4))\n"
"    (set! eighth (floor (/ beat-ms 2)))\n"
"    (set! sixteenth (floor (/ beat-ms 4)))))\n"
"\n"
"(define (get-tempo) *bpm*)\n"
"\n"
"(define (bpm tempo) (floor (/ 60000 tempo)))\n"
"\n"
";; Pitch constants\n"
"(define c0 12) (define cs0 13) (define db0 13) (define d0 14)\n"
"(define ds0 15) (define eb0 15) (define e0 16) (define f0 17)\n"
"(define fs0 18) (define gb0 18) (define g0 19) (define gs0 20)\n"
"(define ab0 20) (define a0 21) (define as0 22) (define bb0 22) (define b0 23)\n"
"\n"
"(define c1 24) (define cs1 25) (define db1 25) (define d1 26)\n"
"(define ds1 27) (define eb1 27) (define e1 28) (define f1 29)\n"
"(define fs1 30) (define gb1 30) (define g1 31) (define gs1 32)\n"
"(define ab1 32) (define a1 33) (define as1 34) (define bb1 34) (define b1 35)\n"
"\n"
"(define c2 36) (define cs2 37) (define db2 37) (define d2 38)\n"
"(define ds2 39) (define eb2 39) (define e2 40) (define f2 41)\n"
"(define fs2 42) (define gb2 42) (define g2 43) (define gs2 44)\n"
"(define ab2 44) (define a2 45) (define as2 46) (define bb2 46) (define b2 47)\n"
"\n"
"(define c3 48) (define cs3 49) (define db3 49) (define d3 50)\n"
"(define ds3 51) (define eb3 51) (define e3 52) (define f3 53)\n"
"(define fs3 54) (define gb3 54) (define g3 55) (define gs3 56)\n"
"(define ab3 56) (define a3 57) (define as3 58) (define bb3 58) (define b3 59)\n"
"\n"
"(define c4 60) (define cs4 61) (define db4 61) (define d4 62)\n"
"(define ds4 63) (define eb4 63) (define e4 64) (define f4 65)\n"
"(define fs4 66) (define gb4 66) (define g4 67) (define gs4 68)\n"
"(define ab4 68) (define a4 69) (define as4 70) (define bb4 70) (define b4 71)\n"
"\n"
"(define c5 72) (define cs5 73) (define db5 73) (define d5 74)\n"
"(define ds5 75) (define eb5 75) (define e5 76) (define f5 77)\n"
"(define fs5 78) (define gb5 78) (define g5 79) (define gs5 80)\n"
"(define ab5 80) (define a5 81) (define as5 82) (define bb5 82) (define b5 83)\n"
"\n"
"(define c6 84) (define cs6 85) (define db6 85) (define d6 86)\n"
"(define ds6 87) (define eb6 87) (define e6 88) (define f6 89)\n"
"(define fs6 90) (define gb6 90) (define g6 91) (define gs6 92)\n"
"(define ab6 92) (define a6 93) (define as6 94) (define bb6 94) (define b6 95)\n"
"\n"
"(define c7 96) (define cs7 97) (define db7 97) (define d7 98)\n"
"(define ds7 99) (define eb7 99) (define e7 100) (define f7 101)\n"
"(define fs7 102) (define gb7 102) (define g7 103) (define gs7 104)\n"
"(define ab7 104) (define a7 105) (define as7 106) (define bb7 106) (define b7 107)\n"
"\n"
"(define c8 108) (define cs8 109) (define db8 109) (define d8 110)\n"
"(define ds8 111) (define eb8 111) (define e8 112) (define f8 113)\n"
"(define fs8 114) (define gb8 114) (define g8 115) (define gs8 116)\n"
"(define ab8 116) (define a8 117) (define as8 118) (define bb8 118) (define b8 119)\n"
"\n"
";; ============================================================================\n"
";; Scale intervals (semitones from root)\n"
";; ============================================================================\n"
"\n"
";; Diatonic modes\n"
"(define scale-major '(0 2 4 5 7 9 11))\n"
"(define scale-ionian scale-major)\n"
"(define scale-dorian '(0 2 3 5 7 9 10))\n"
"(define scale-phrygian '(0 1 3 5 7 8 10))\n"
"(define scale-lydian '(0 2 4 6 7 9 11))\n"
"(define scale-mixolydian '(0 2 4 5 7 9 10))\n"
"(define scale-minor '(0 2 3 5 7 8 10))\n"
"(define scale-aeolian scale-minor)\n"
"(define scale-locrian '(0 1 3 5 6 8 10))\n"
"\n"
";; Other minor scales\n"
"(define scale-harmonic-minor '(0 2 3 5 7 8 11))\n"
"(define scale-melodic-minor '(0 2 3 5 7 9 11))\n"
"\n"
";; Pentatonic\n"
"(define scale-pentatonic '(0 2 4 7 9))\n"
"(define scale-pentatonic-major scale-pentatonic)\n"
"(define scale-pentatonic-minor '(0 3 5 7 10))\n"
"\n"
";; Blues\n"
"(define scale-blues '(0 3 5 6 7 10))\n"
"\n"
";; Symmetric\n"
"(define scale-whole-tone '(0 2 4 6 8 10))\n"
"(define scale-chromatic '(0 1 2 3 4 5 6 7 8 9 10 11))\n"
"(define scale-diminished-hw '(0 1 3 4 6 7 9 10))\n"
"(define scale-diminished-wh '(0 2 3 5 6 8 9 11))\n"
"(define scale-augmented '(0 3 4 7 8 11))\n"
"\n"
";; Bebop\n"
"(define scale-bebop-dominant '(0 2 4 5 7 9 10 11))\n"
"(define scale-bebop-major '(0 2 4 5 7 8 9 11))\n"
"(define scale-bebop-minor '(0 2 3 5 7 8 9 10))\n"
"\n"
";; Exotic/World\n"
"(define scale-hungarian-minor '(0 2 3 6 7 8 11))\n"
"(define scale-double-harmonic '(0 1 4 5 7 8 11))\n"
"(define scale-neapolitan-major '(0 1 3 5 7 9 11))\n"
"(define scale-neapolitan-minor '(0 1 3 5 7 8 11))\n"
"(define scale-phrygian-dominant '(0 1 4 5 7 8 10))\n"
"(define scale-persian '(0 1 4 5 6 8 11))\n"
"(define scale-altered '(0 1 3 4 6 8 10))\n"
"(define scale-enigmatic '(0 1 4 6 8 10 11))\n"
"\n"
";; Japanese\n"
"(define scale-hirajoshi '(0 2 3 7 8))\n"
"(define scale-in-sen '(0 1 5 7 10))\n"
"(define scale-iwato '(0 1 5 6 10))\n"
"(define scale-kumoi '(0 2 3 7 9))\n"
"\n"
";; Other world scales\n"
"(define scale-egyptian '(0 2 5 7 10))\n"
"(define scale-romanian-minor '(0 2 3 6 7 9 10))\n"
"(define scale-spanish-8-tone '(0 1 3 4 5 6 8 10))\n"
"\n"
";; Arabic Maqamat (12-TET approximations)\n"
"(define scale-maqam-hijaz '(0 1 4 5 7 8 10))\n"
"(define scale-maqam-nahawand '(0 2 3 5 7 8 11))\n"
"(define scale-maqam-nikriz '(0 2 3 6 7 9 10))\n"
"(define scale-maqam-athar-kurd '(0 1 3 5 6 8 10))\n"
"(define scale-maqam-shawq-afza '(0 2 3 6 7 9 11))\n"
"(define scale-maqam-jiharkah '(0 2 4 5 7 9 10))\n"
"\n"
";; Indian Ragas (12-TET approximations)\n"
"(define scale-raga-bhairav '(0 1 4 5 7 8 11))\n"
"(define scale-raga-todi '(0 1 3 6 7 8 11))\n"
"(define scale-raga-marwa '(0 1 4 6 7 9 11))\n"
"(define scale-raga-purvi '(0 1 4 6 7 8 11))\n"
"(define scale-raga-charukeshi '(0 2 4 5 7 8 10))\n"
"(define scale-raga-asavari '(0 2 3 5 7 8 10))\n"
"(define scale-raga-bilawal '(0 2 4 5 7 9 11))\n"
"(define scale-raga-khamaj '(0 2 4 5 7 9 10))\n"
"(define scale-raga-kalyan '(0 2 4 6 7 9 11))\n"
"(define scale-raga-bhimpalasi '(0 3 5 7 10))\n"
"(define scale-raga-darbari '(0 2 3 5 7 8 9))\n"
"\n"
";; ============================================================================\n"
";; Microtonal scales (cents-based, for use with pitch-bend)\n"
";; ============================================================================\n"
"\n"
";; Arabic Maqamat with quarter tones\n"
"(define scale-maqam-bayati-cents '(0 150 300 500 700 800 1000))\n"
"(define scale-maqam-rast-cents '(0 200 350 500 700 900 1050))\n"
"(define scale-maqam-saba-cents '(0 150 300 400 500 700 800))\n"
"(define scale-maqam-sikah-cents '(0 150 350 500 650 850 1000))\n"
"(define scale-maqam-huzam-cents '(0 150 350 500 700 850 1050))\n"
"(define scale-maqam-iraq-cents '(0 150 350 500 700 850 1000))\n"
"(define scale-maqam-bastanikar-cents '(0 150 350 500 700 800 1000))\n"
"\n"
";; Turkish Makamlar\n"
"(define scale-makam-ussak-cents '(0 150 300 500 700 800 1000))\n"
"(define scale-makam-huseyni-cents '(0 150 300 500 700 900 1000))\n"
"\n"
";; Indian 22-Shruti scale\n"
"(define scale-shruti-cents '(0 90 112 182 204 294 316 386 408 498 520 590\n"
"                             612 702 792 814 884 906 996 1018 1088 1110))\n"
"\n"
";; ============================================================================\n"
";; Scale name lookup table\n"
";; ============================================================================\n"
"\n"
"(define *scales*\n"
"  (list\n"
"    (cons 'major scale-major)\n"
"    (cons 'ionian scale-ionian)\n"
"    (cons 'dorian scale-dorian)\n"
"    (cons 'phrygian scale-phrygian)\n"
"    (cons 'lydian scale-lydian)\n"
"    (cons 'mixolydian scale-mixolydian)\n"
"    (cons 'minor scale-minor)\n"
"    (cons 'aeolian scale-aeolian)\n"
"    (cons 'locrian scale-locrian)\n"
"    (cons 'harmonic-minor scale-harmonic-minor)\n"
"    (cons 'melodic-minor scale-melodic-minor)\n"
"    (cons 'pentatonic scale-pentatonic)\n"
"    (cons 'pentatonic-major scale-pentatonic-major)\n"
"    (cons 'pentatonic-minor scale-pentatonic-minor)\n"
"    (cons 'blues scale-blues)\n"
"    (cons 'whole-tone scale-whole-tone)\n"
"    (cons 'chromatic scale-chromatic)\n"
"    (cons 'diminished-hw scale-diminished-hw)\n"
"    (cons 'diminished-wh scale-diminished-wh)\n"
"    (cons 'augmented scale-augmented)\n"
"    (cons 'bebop-dominant scale-bebop-dominant)\n"
"    (cons 'bebop-major scale-bebop-major)\n"
"    (cons 'bebop-minor scale-bebop-minor)\n"
"    (cons 'hungarian-minor scale-hungarian-minor)\n"
"    (cons 'double-harmonic scale-double-harmonic)\n"
"    (cons 'neapolitan-major scale-neapolitan-major)\n"
"    (cons 'neapolitan-minor scale-neapolitan-minor)\n"
"    (cons 'phrygian-dominant scale-phrygian-dominant)\n"
"    (cons 'persian scale-persian)\n"
"    (cons 'altered scale-altered)\n"
"    (cons 'enigmatic scale-enigmatic)\n"
"    (cons 'hirajoshi scale-hirajoshi)\n"
"    (cons 'in-sen scale-in-sen)\n"
"    (cons 'iwato scale-iwato)\n"
"    (cons 'kumoi scale-kumoi)\n"
"    (cons 'egyptian scale-egyptian)\n"
"    (cons 'romanian-minor scale-romanian-minor)\n"
"    (cons 'spanish-8-tone scale-spanish-8-tone)\n"
"    (cons 'maqam-hijaz scale-maqam-hijaz)\n"
"    (cons 'maqam-nahawand scale-maqam-nahawand)\n"
"    (cons 'maqam-nikriz scale-maqam-nikriz)\n"
"    (cons 'maqam-athar-kurd scale-maqam-athar-kurd)\n"
"    (cons 'maqam-shawq-afza scale-maqam-shawq-afza)\n"
"    (cons 'maqam-jiharkah scale-maqam-jiharkah)\n"
"    (cons 'raga-bhairav scale-raga-bhairav)\n"
"    (cons 'raga-todi scale-raga-todi)\n"
"    (cons 'raga-marwa scale-raga-marwa)\n"
"    (cons 'raga-purvi scale-raga-purvi)\n"
"    (cons 'raga-charukeshi scale-raga-charukeshi)\n"
"    (cons 'raga-asavari scale-raga-asavari)\n"
"    (cons 'raga-bilawal scale-raga-bilawal)\n"
"    (cons 'raga-khamaj scale-raga-khamaj)\n"
"    (cons 'raga-kalyan scale-raga-kalyan)\n"
"    (cons 'raga-bhimpalasi scale-raga-bhimpalasi)\n"
"    (cons 'raga-darbari scale-raga-darbari)))\n"
"\n"
";; ============================================================================\n"
";; Scale helper functions\n"
";; ============================================================================\n"
"\n"
"(define (get-scale name)\n"
"  \"Look up scale intervals by name symbol\"\n"
"  (let ((entry (assq name *scales*)))\n"
"    (if entry (cdr entry)\n"
"        (error 'unknown-scale \"Unknown scale name\" name))))\n"
"\n"
"(define (scale root name)\n"
"  \"Build a scale from root and scale name. E.g. (scale c4 'major)\"\n"
"  (build-scale root (get-scale name)))\n"
"\n"
"(define (degree root name n)\n"
"  \"Get the nth degree of a named scale. E.g. (degree c4 'major 5)\"\n"
"  (scale-degree root (get-scale name) n))\n"
"\n"
"(define (in-scale-named? pitch root name)\n"
"  \"Check if pitch is in named scale. E.g. (in-scale-named? e4 c4 'major)\"\n"
"  (in-scale? pitch root (get-scale name)))\n"
"\n"
"(define (quantize pitch root name)\n"
"  \"Quantize pitch to named scale. E.g. (quantize fs4 c4 'major)\"\n"
"  (quantize-to-scale pitch root (get-scale name)))\n"
"\n"
";; Microtonal helper: convert cents interval to note + bend\n"
"(define (cents-to-note root cents)\n"
"  \"Convert cents interval to (note . bend-cents) pair\"\n"
"  (let* ((semitones (floor (/ cents 100)))\n"
"         (bend-cents (modulo cents 100)))\n"
"    (if (> bend-cents 50)\n"
"        (cons (+ root semitones 1) (- bend-cents 100))\n"
"        (cons (+ root semitones) bend-cents))))\n"
"\n"
";; ============================================================================\n"
";; Chord builders\n"
";; ============================================================================\n"
"\n"
"(define (major root)\n"
"  (let ((r (if (number? root) root (note root))))\n"
"    (list r (+ r 4) (+ r 7))))\n"
"\n"
"(define (minor root)\n"
"  (let ((r (if (number? root) root (note root))))\n"
"    (list r (+ r 3) (+ r 7))))\n"
"\n"
"(define (dim root)\n"
"  (let ((r (if (number? root) root (note root))))\n"
"    (list r (+ r 3) (+ r 6))))\n"
"\n"
"(define (aug root)\n"
"  (let ((r (if (number? root) root (note root))))\n"
"    (list r (+ r 4) (+ r 8))))\n"
"\n"
"(define (dom7 root)\n"
"  (let ((r (if (number? root) root (note root))))\n"
"    (list r (+ r 4) (+ r 7) (+ r 10))))\n"
"\n"
"(define (maj7 root)\n"
"  (let ((r (if (number? root) root (note root))))\n"
"    (list r (+ r 4) (+ r 7) (+ r 11))))\n"
"\n"
"(define (min7 root)\n"
"  (let ((r (if (number? root) root (note root))))\n"
"    (list r (+ r 3) (+ r 7) (+ r 10))))\n"
"\n"
";; Transpose helpers\n"
"(define (transpose pitch semitones)\n"
"  (let ((p (if (number? pitch) pitch (note pitch))))\n"
"    (+ p semitones)))\n"
"\n"
"(define (octave-up pitch) (transpose pitch 12))\n"
"(define (octave-down pitch) (transpose pitch -12))\n"
"\n"
";; Arpeggio helper\n"
"(define (midi-arpeggio m pitches . args)\n"
"  (let ((vel (if (>= (length args) 1) (car args) mf))\n"
"        (dur (if (>= (length args) 2) (cadr args) eighth))\n"
"        (ch (if (>= (length args) 3) (caddr args) 1)))\n"
"    (for-each (lambda (p) (midi-note m p vel dur ch)) pitches)))\n"
"\n"
";; Rest helper\n"
"(define (rest . args)\n"
"  (let ((dur (if (null? args) quarter (car args))))\n"
"    (midi-sleep dur)))\n"
"\n"
";; ============================================================================\n"
";; REPL convenience functions (use global *midi* output)\n"
";; ============================================================================\n"
"(define *midi* #f)\n"
"\n"
"(define (open . args)\n"
"  \"Open MIDI port and set as default. (open) or (open name) or (open index)\"\n"
"  (if *midi* (midi-close *midi*))\n"
"  (set! *midi* (if (null? args) (midi-open) (midi-open (car args))))\n"
"  *midi*)\n"
"\n"
"(define (close)\n"
"  \"Close default MIDI port\"\n"
"  (if *midi* (begin (midi-close *midi*) (set! *midi* #f))))\n"
"\n"
"(define (n pitch . args)\n"
"  \"Play note on default port: (n pitch [vel] [dur] [ch])\"\n"
"  (if (not *midi*) (error 'no-midi-port \"No MIDI port open. Use (open) first.\"))\n"
"  (let ((vel (if (>= (length args) 1) (car args) mf))\n"
"        (dur (if (>= (length args) 2) (cadr args) quarter))\n"
"        (ch (if (>= (length args) 3) (caddr args) 1)))\n"
"    (midi-note *midi* pitch vel dur ch)))\n"
"\n"
"(define (ch pitches . args)\n"
"  \"Play chord on default port: (ch pitches [vel] [dur] [channel])\"\n"
"  (if (not *midi*) (error 'no-midi-port \"No MIDI port open. Use (open) first.\"))\n"
"  (let ((vel (if (>= (length args) 1) (car args) mf))\n"
"        (dur (if (>= (length args) 2) (cadr args) quarter))\n"
"        (channel (if (>= (length args) 3) (caddr args) 1)))\n"
"    (midi-chord *midi* pitches vel dur channel)))\n"
"\n"
"(define (arp pitches . args)\n"
"  \"Arpeggiate on default port: (arp pitches [vel] [dur] [ch])\"\n"
"  (if (not *midi*) (error 'no-midi-port \"No MIDI port open. Use (open) first.\"))\n"
"  (let ((vel (if (>= (length args) 1) (car args) mf))\n"
"        (dur (if (>= (length args) 2) (cadr args) eighth))\n"
"        (channel (if (>= (length args) 3) (caddr args) 1)))\n"
"    (midi-arpeggio *midi* pitches vel dur channel)))\n"
"\n"
"(define (play-notes ns)\n"
"	\"Play a list of notes\"\n"
"	(if (not *midi*) (error 'no-midi-port \"No MIDI port open. Use (open) first.\"))\n"
"	(map n ns))\n"
"\n"
";; ============================================================================\n"
";; Generative Music Functions\n"
";; ============================================================================\n"
"\n"
";; Pure PRNG using Linear Congruential Generator (same constants as glibc)\n"
";; Returns (value . next-seed)\n"
"(define (next-random seed)\n"
"  (let* ((next-seed (modulo (+ (* seed 1103515245) 12345) 2147483648))\n"
"         (value (floor (/ next-seed 65536))))\n"
"    (cons value next-seed)))\n"
"\n"
";; Generate random int in range [lo, hi]. Returns (value . next-seed)\n"
"(define (random-range seed lo hi)\n"
"  (if (>= lo hi)\n"
"      (cons lo seed)\n"
"      (let* ((result (next-random seed))\n"
"             (r (car result))\n"
"             (next-seed (cdr result)))\n"
"        (cons (+ lo (modulo r (+ 1 (- hi lo)))) next-seed))))\n"
"\n"
";; Generate n random ints in range [lo, hi]. Returns (list . next-seed)\n"
"(define (random-list seed n lo hi)\n"
"  (let loop ((s seed) (count n) (acc '()))\n"
"    (if (<= count 0)\n"
"        (cons (reverse acc) s)\n"
"        (let* ((result (random-range s lo hi))\n"
"               (r (car result))\n"
"               (next-s (cdr result)))\n"
"          (loop next-s (- count 1) (cons r acc))))))\n"
"\n"
";; Euclidean rhythm using Bjorklund's algorithm\n"
";; Returns a list of booleans where #t = hit, #f = rest\n"
"(define (euclidean hits steps)\n"
"  (cond\n"
"    ((<= hits 0) (make-list steps #f))\n"
"    ((>= hits steps) (make-list steps #t))\n"
"    (else\n"
"     (let loop ((seqs (map list (make-list hits #t)))\n"
"                (remainder (map list (make-list (- steps hits) #f))))\n"
"       (if (<= (length remainder) 1)\n"
"           ;; Flatten and return\n"
"           (apply append (append seqs remainder))\n"
"           ;; Bjorklund step\n"
"           (let* ((min-len (min (length seqs) (length remainder)))\n"
"                  (new-seqs (map (lambda (s r) (append s r))\n"
"                                 (take seqs min-len)\n"
"                                 (take remainder min-len)))\n"
"                  (new-remainder (append (drop seqs min-len)\n"
"                                        (drop remainder min-len))))\n"
"             (loop new-seqs new-remainder)))))))\n"
"\n"
";; Helper: take first n elements\n"
"(define (take lst n)\n"
"  (if (or (<= n 0) (null? lst))\n"
"      '()\n"
"      (cons (car lst) (take (cdr lst) (- n 1)))))\n"
"\n"
";; Helper: drop first n elements\n"
"(define (drop lst n)\n"
"  (if (or (<= n 0) (null? lst))\n"
"      lst\n"
"      (drop (cdr lst) (- n 1))))\n"
"\n"
";; Helper: make a list of n copies of x\n"
"(define (make-list n x)\n"
"  (if (<= n 0)\n"
"      '()\n"
"      (cons x (make-list (- n 1) x))))\n"
"\n"
";; Arpeggio patterns\n"
"(define (arp-up lst)\n"
"  \"Ascending arpeggio pattern - returns copy of list\"\n"
"  (map (lambda (x) x) lst))\n"
"\n"
"(define (arp-down lst)\n"
"  \"Descending arpeggio pattern - returns reversed list\"\n"
"  (reverse lst))\n"
"\n"
"(define (arp-up-down lst)\n"
"  \"Up-down arpeggio pattern (no repeated top note)\"\n"
"  (if (<= (length lst) 1)\n"
"      lst\n"
"      (append lst (reverse (cdr (reverse (cdr lst)))))))\n"
"\n"
";; Retrograde - reverse a list\n"
"(define (retrograde lst)\n"
"  \"Reverse a list of pitches\"\n"
"  (reverse lst))\n"
"\n"
";; Melodic inversion around an axis pitch\n"
"(define (invert lst axis)\n"
"  \"Melodic inversion around an axis pitch\"\n"
"  (map (lambda (pitch) (- (* 2 axis) pitch)) lst))\n"
"\n"
";; Fisher-Yates shuffle using seed. Returns shuffled list.\n"
"(define (shuffle seed lst)\n"
"  (let ((vec (list->vector lst)))\n"
"    (let loop ((s seed) (i (- (vector-length vec) 1)))\n"
"      (if (<= i 0)\n"
"          (vector->list vec)\n"
"          (let* ((result (random-range s 0 i))\n"
"                 (j (car result))\n"
"                 (next-s (cdr result))\n"
"                 (tmp (vector-ref vec i)))\n"
"            (vector-set! vec i (vector-ref vec j))\n"
"            (vector-set! vec j tmp)\n"
"            (loop next-s (- i 1)))))))\n"
"\n"
";; Pick one element from a list using seed\n"
"(define (pick seed lst)\n"
"  (if (null? lst)\n"
"      #f\n"
"      (let* ((result (random-range seed 0 (- (length lst) 1)))\n"
"             (idx (car result)))\n"
"        (list-ref lst idx))))\n"
"\n"
";; Pick n elements from a list (with replacement)\n"
"(define (pick-n seed n lst)\n"
"  (if (null? lst)\n"
"      '()\n"
"      (let loop ((s seed) (count n) (acc '()))\n"
"        (if (<= count 0)\n"
"            (reverse acc)\n"
"            (let* ((result (random-range s 0 (- (length lst) 1)))\n"
"                   (idx (car result))\n"
"                   (next-s (cdr result)))\n"
"              (loop next-s (- count 1) (cons (list-ref lst idx) acc)))))))\n"
"\n"
";; Random walk - start from a pitch, take n steps of max size\n"
";; Returns list of pitches\n"
"(define (random-walk seed start max-step n)\n"
"  (let loop ((s seed) (pitch start) (count n) (acc '()))\n"
"    (if (<= count 0)\n"
"        (reverse acc)\n"
"        (let* ((result (random-range s (- max-step) max-step))\n"
"               (step (car result))\n"
"               (next-s (cdr result))\n"
"               (new-pitch (max 0 (min 127 (+ pitch step)))))\n"
"          (loop next-s new-pitch (- count 1) (cons pitch acc))))))\n"
"\n"
";; Drunk walk constrained to scale pitches\n"
";; Returns list of pitches from the scale\n"
"(define (drunk-walk seed start scale-pitches max-degrees n)\n"
"  (if (null? scale-pitches)\n"
"      '()\n"
"      (let* ((find-closest\n"
"              (lambda (p pitches)\n"
"                (let loop ((ps pitches) (idx 0) (best-idx 0) (best-dist 999999))\n"
"                  (if (null? ps)\n"
"                      best-idx\n"
"                      (let ((dist (abs (- p (car ps)))))\n"
"                        (if (< dist best-dist)\n"
"                            (loop (cdr ps) (+ idx 1) idx dist)\n"
"                            (loop (cdr ps) (+ idx 1) best-idx best-dist)))))))\n"
"             (scale-len (length scale-pitches))\n"
"             (start-idx (find-closest start scale-pitches)))\n"
"        (let loop ((s seed) (idx start-idx) (count n) (acc '()))\n"
"          (if (<= count 0)\n"
"              (reverse acc)\n"
"              (let* ((result (random-range s (- max-degrees) max-degrees))\n"
"                     (step (car result))\n"
"                     (next-s (cdr result))\n"
"                     (new-idx (max 0 (min (- scale-len 1) (+ idx step)))))\n"
"                (loop next-s new-idx (- count 1)\n"
"                      (cons (list-ref scale-pitches idx) acc))))))))\n"
"\n"
";; Weighted random selection\n"
";; weights is a list of (value . weight) pairs\n"
"(define (weighted-pick seed weights)\n"
"  (let ((total (apply + (map cdr weights))))\n"
"    (if (<= total 0)\n"
"        #f\n"
"        (let* ((result (random-range seed 1 total))\n"
"               (r (car result)))\n"
"          (let loop ((ws weights) (cumulative 0))\n"
"            (if (null? ws)\n"
"                (caar (reverse weights))\n"
"                (let ((new-cumulative (+ cumulative (cdar ws))))\n"
"                  (if (<= r new-cumulative)\n"
"                      (caar ws)\n"
"                      (loop (cdr ws) new-cumulative)))))))))\n"
"\n"
";; Probability gate - returns (result . next-seed) with given probability (0-100)\n"
"(define (chance seed probability)\n"
"  (let* ((result (random-range seed 0 99))\n"
"         (r (car result))\n"
"         (next-seed (cdr result)))\n"
"    (cons (< r probability) next-seed)))\n";
